dataset:
    base_path: "F:\\pychramCode3\\myself\\deepfashion2_select160"
#    base_path: "/home/user/Downloads/gc/pspnet/pspnet-pytorch-master_better/deepfashion2_select77848"
    dataset_name: "deepfashion"
image:
    out_stride: 16
    base_size: 512
    crop_size: 512
network:
    backbone: "mobilenet"  #choices=['resnet50', 'mobilenet']
    sync_bn: false
    freeze_bn: false
    use_cuda: True
    num_classes: 14
training:
    workers: 1
    loss_type: "ce"   #choices=['ce', 'focal']
    epochs: 16
    start_epoch: 0
    batch_size: 4
    use_balanced_weights: false
    lr: 0.0007
    lr_scheduler: "poly"     #choices=['poly', 'step', 'cos']
    momentum: 0.9
    weight_decay: 0.0005
    nesterov: false
    callbacks:
    weights_initialization:
        use_pretrained_weights: false
        restore_from: "./experiments/checkpoint_last.pth"
    model_best_checkpoint:
        enabled: true
        out_file: "./experiments/checkpoint_best.pth"
        monitor: "val_loss"
    model_last_checkpoint:
        enabled: true
        out_file: "./experiments/checkpoint_last.pth"
    train_on_subset:
        enabled: false
        dataset_fraction: 1
    output:
        output_weights: "./snapshots/checkpoint_best.pth"
    tensorboard: 
        enabled: false
        log_dir: "./tensorboard/"
    no_val: false
    val_interval: 1
inference:
    batch_size: 2
