dataset:
    base_path: "/root/zhonghao/gongchuang/myproject/fastfcn/dataset/deepfashion2_test100"
    #base_path: "/root/zhonghao/gongchuang/myproject/fastfcn/dataset/deepfashion2_select77848"
    dataset_name: "deepfashion"
image:
    out_stride: 16
    base_size: 512
    crop_size: 512
training:
    batch_size: 2
    val_batch_size: 2
    start_epoch: 0
    epochs: 100
    workers: 1
    tensorboard:
      enabled: false
      log_dir: "./tensorboard/three_attention"
    no_val: false
    val_interval: 1
network:
    backbone: "hrnet"  #hrnet
    sync_bn: false
    freeze_bn: false
    use_cuda: True
    num_classes: 14
MODEL:
  NAME: seg_hrnet_ocr
  NUM_OUTPUTS: 2
  PRETRAINED: 'pretrained_models/hrnetv2_w48_imagenet_pretrained.pth'
  EXTRA:
    FINAL_CONV_KERNEL: 1
    STAGE1:
      NUM_MODULES: 1
      NUM_RANCHES: 1
      BLOCK: BOTTLENECK
      NUM_BLOCKS:
      - 4
      NUM_CHANNELS:
      - 64
      FUSE_METHOD: SUM
    STAGE2:
      NUM_MODULES: 1
      NUM_BRANCHES: 2
      BLOCK: BASIC
      NUM_BLOCKS:
      - 4
      - 4
      NUM_CHANNELS:
      - 48
      - 96
      FUSE_METHOD: SUM
    STAGE3:
      NUM_MODULES: 4
      NUM_BRANCHES: 3
      BLOCK: BASIC
      NUM_BLOCKS:
      - 4
      - 4
      - 4
      NUM_CHANNELS:
      - 48
      - 96
      - 192
      FUSE_METHOD: SUM
    STAGE4:
      NUM_MODULES: 3
      NUM_BRANCHES: 4
      BLOCK: BASIC
      NUM_BLOCKS:
      - 4
      - 4
      - 4
      - 4
      NUM_CHANNELS:
      - 48
      - 96
      - 192
      - 384
      FUSE_METHOD: SUM